apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-api
  labels:
    name: pizzaria-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaria-api
      tier: backend
  template:
    metadata:
      labels:
        app: pizzaria-api
        tier: backend
        app.kubernetes.io/created-by: kalilventura
    spec:
      containers:
      - name: pizzaria-api
        image: kalilventura/pizzaria:3.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "3Gi"
            cpu: "1500m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pizzaria-configmap
        - secretRef:
            name: pizzaria-secrets
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pizzaria-configmap
              key: hostname
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: pizzaria-configmap
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: pizzaria-configmap
              key: databasename
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: pizzaria-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pizzaria-secrets
              key: password
        # Initial probe
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 50
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        # Once the container is up, test using HTTP health check
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 50
          failureThreshold: 5
          timeoutSeconds: 5
