apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-api
  labels:
    name: pizzaria-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaria-api
      tier: backend
  template:
    metadata:
      labels:
        app: pizzaria-api
        tier: backend
        app.kubernetes.io/created-by: kalilventura
    spec:
      containers:
      - name: pizzaria-api
        image: kalilventura/pizzaria:3.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http8080
        envFrom:
        - configMapRef:
            name: pizzaria-api-configmap
        - secretRef:
            name: pizzaria-api-secrets
