apiVersion: v1
kind: Service
metadata:
  name: pizzaria-api
  labels:
    app: pizzaria-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: pizzaria-api
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 # Service port (exposed to the app)
    targetPort: 8080 # Container port (PostgreSQL port inside the pod)
    nodePort: 30163
