apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-db
  labels:
    name: pizzaria-db
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaria-db
      tier: database
  template:
    metadata:
      labels:
        app: pizzaria-db
        tier: database
        app.kubernetes.io/created-by: kalilventura
    spec:
      containers:
      - name: pizzaria-db
        image: postgres:16.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: pizzaria-db-config
        - secretRef:
            name: pizzaria-db-secrets
        resources:
          limits:
            memory: "256Mi"
            cpu: "800m"
        volumeMounts:
        - name: pizzaria-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pizzaria-db-storage
        persistentVolumeClaim:
          claimName: pizzaria-db-pvc
