apiVersion: v1
kind: PersistentVolume
metadata:
  name: pizzaria-db-pv
  labels:
    app: pizzaria-db
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate
