apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pizzaria-db-pvc
  labels:
    app: pizzaria-db
    tier: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
