apiVersion: v1
kind: Service
metadata:
  name: pizzaria-db # DNS Name
  labels:
    app: pizzaria-db
    tier: database
spec:
  clusterIP: None # We Use DNS, Thus ClusterIP is not relevant
  selector:
    app: pizzaria-db
    tier: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
