apiVersion: v1
kind: Service
metadata:
  name: pizzaria-db # DNS Name
  labels:
    app: pizzaria-db
    tier: database
spec:
  selector:
    app: pizzaria-db
    tier: database
  ports:
  - port: 5432 # Service port (exposed to the app)
    targetPort: 5432 # Container port (PostgreSQL port inside the pod)
