services:
  server:
    container_name: bacco_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=baccodb
      - DB_PORT=5432
      - DB_NAME=bacco
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - app-k8s-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      baccodb:
        condition: service_healthy
  baccodb:
    container_name: postgres
    image: postgres:16.4
    restart: always
    volumes:
      - bacco-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bacco
    ports:
      - "5432:5432"
    networks:
      - app-k8s-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bacco-db-data:

networks:
  app-k8s-network:
